import Foundation
import UIKit

enum AccidentEvidencePackBuilder {
    struct Input {
        let vehicleName: String
        let vehicleKind: VehicleKind
        let ownRegistration: String
        let insurerName: String
        let insurerPolicyNumber: String
        let insurerClaimsPhone: String
        let record: AccidentRecord
        let photoImages: [(AccidentPhotoKind, UIImage)]
    }

    static func buildPDF(input: Input) -> Data {
        let pageBounds = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: pageBounds)
        let guidance = AccidentGuidance.evaluate(
            AccidentStore.guidanceInput(for: input.record, profile: nil)
        )

        return renderer.pdfData { context in
            var y: CGFloat = 48
            let margin: CGFloat = 48
            let contentWidth = pageBounds.width - margin * 2

            func beginPageIfNeeded(requiredHeight: CGFloat) {
                if y + requiredHeight > pageBounds.height - margin {
                    context.beginPage()
                    y = margin
                }
            }

            func drawTitle(_ text: String) {
                beginPageIfNeeded(requiredHeight: 28)
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.boldSystemFont(ofSize: 20),
                    .foregroundColor: UIColor.label
                ]
                text.draw(at: CGPoint(x: margin, y: y), withAttributes: attrs)
                y += 28
            }

            func drawBody(_ text: String, bold: Bool = false) {
                let font = bold ? UIFont.boldSystemFont(ofSize: 12) : UIFont.systemFont(ofSize: 12)
                let paragraph = NSMutableParagraphStyle()
                paragraph.lineBreakMode = .byWordWrapping
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: UIColor.label,
                    .paragraphStyle: paragraph
                ]
                let measured = (text as NSString).boundingRect(
                    with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attrs,
                    context: nil
                )
                beginPageIfNeeded(requiredHeight: measured.height + 8)
                (text as NSString).draw(
                    in: CGRect(x: margin, y: y, width: contentWidth, height: measured.height),
                    withAttributes: attrs
                )
                y += measured.height + 8
            }

            context.beginPage()
            drawTitle("Accident incident pack")
            drawBody("Generated by Lyneqo Caravan & Motorhome on \(Formatters.dateTime(Date()))")
            drawBody(AccidentGuidance.helperDisclaimer)

            drawBody("Your vehicle", bold: true)
            drawBody(input.vehicleName.isEmpty ? input.vehicleKind.displayName : input.vehicleName)
            drawBody(input.vehicleKind.displayName)
            if !input.ownRegistration.isEmpty {
                drawBody("Registration: \(input.ownRegistration)")
            }
            if !input.insurerName.isEmpty {
                drawBody("Insurer: \(input.insurerName)")
            }
            if !input.insurerPolicyNumber.isEmpty {
                drawBody("Policy: \(input.insurerPolicyNumber)")
            }
            if !input.insurerClaimsPhone.isEmpty {
                drawBody("Claims phone: \(input.insurerClaimsPhone)")
            }

            drawBody("Incident", bold: true)
            drawBody("When: \(Formatters.dateTime(input.record.occurredAt))")
            drawBody("Where: \(input.record.jurisdiction.displayName)")
            if !input.record.locationDescription.isEmpty {
                drawBody(input.record.locationDescription)
            }
            if !input.record.what3Words.isEmpty {
                drawBody("What3Words: \(input.record.what3Words)")
            }
            if input.record.hasCoordinate {
                drawBody(String(format: "Coordinates: %.5f, %.5f", input.record.latitude, input.record.longitude))
            }
            drawBody("Process used: \(input.record.processBranch.displayName)")
            drawBody("Anyone injured: \(input.record.anyoneInjured ? "Yes" : "No / not sure")")
            drawBody("Details exchanged: \(input.record.detailsExchanged ? "Yes" : "Not yet")")
            drawBody("Police reported: \(input.record.policeReported ? "Yes" : "No")")
            if !input.record.policeReference.isEmpty {
                drawBody("Police reference: \(input.record.policeReference)")
            }
            drawBody("Insurer notified: \(input.record.insurerNotified ? "Yes" : "No")")
            if !input.record.weatherNotes.isEmpty {
                drawBody("Weather / conditions: \(input.record.weatherNotes)")
            }
            if !input.record.factualNotes.isEmpty {
                drawBody("Factual notes: \(input.record.factualNotes)")
            }
            if !input.record.easCircumstancesNotes.isEmpty {
                drawBody("Accident statement notes: \(input.record.easCircumstancesNotes)")
            }

            drawBody("Other vehicles", bold: true)
            if input.record.otherVehiclesList.isEmpty {
                drawBody("No other vehicles recorded.")
            } else {
                for vehicle in input.record.otherVehiclesList {
                    drawBody(vehicle.displayRegistration, bold: true)
                    if vehicle.isForeignRegistration {
                        drawBody("Foreign registration (\(vehicle.registrationCountry.isEmpty ? "country not recorded" : vehicle.registrationCountry))")
                    }
                    if !vehicle.driverName.isEmpty { drawBody("Driver: \(vehicle.driverName)") }
                    if !vehicle.driverPhone.isEmpty { drawBody("Driver phone: \(vehicle.driverPhone)") }
                    if !vehicle.driverAddress.isEmpty { drawBody("Driver address: \(vehicle.driverAddress)") }
                    if !vehicle.ownerName.isEmpty { drawBody("Owner: \(vehicle.ownerName)") }
                    if !vehicle.insurerName.isEmpty { drawBody("Insurer: \(vehicle.insurerName)") }
                    if !vehicle.insurancePolicyNumber.isEmpty { drawBody("Policy: \(vehicle.insurancePolicyNumber)") }
                    if !vehicle.greenCardNumber.isEmpty { drawBody("Green Card: \(vehicle.greenCardNumber)") }
                    if !vehicle.lookupMake.isEmpty || !vehicle.lookupModel.isEmpty {
                        drawBody("Lookup: \([vehicle.lookupMake, vehicle.lookupModel, vehicle.lookupColour].filter { !$0.isEmpty }.joined(separator: " "))")
                    }
                    if !vehicle.lookupMotStatus.isEmpty {
                        drawBody("MOT: \(vehicle.lookupMotStatus)")
                    }
                    if !vehicle.lookupTaxStatus.isEmpty {
                        drawBody("Tax: \(vehicle.lookupTaxStatus)")
                    }
                    if let checked = vehicle.lookupCheckedAt {
                        drawBody(Formatters.checkedAtCaption(checked))
                    }
                    if !vehicle.redFlags.isEmpty {
                        drawBody("Red flags: \(vehicle.redFlags.map(\.displayName).joined(separator: ", "))")
                    }
                }
            }

            drawBody("CCTV and video", bold: true)
            drawBody("Witness footage mentioned: \(input.record.cctvWitnessesMentioned ? "Yes" : "No")")
            drawBody("CCTV visible nearby: \(input.record.cctvNearbyVisible ? "Yes" : "No")")
            drawBody("Nearby uninvolved lorry/HGV cameras: \(input.record.cctvNearbyLorry ? "Yes" : "No")")
            if !input.record.cctvNotes.isEmpty {
                drawBody(input.record.cctvNotes)
            }

            drawBody("Witnesses", bold: true)
            if input.record.witnessesList.isEmpty {
                drawBody("No witnesses recorded.")
            } else {
                for witness in input.record.witnessesList {
                    let name = witness.name.isEmpty ? "Witness" : witness.name
                    let phone = witness.phone.isEmpty ? "" : " · \(witness.phone)"
                    let footage = witness.hasFootage ? " · has video/CCTV" : ""
                    drawBody("\(name)\(phone)\(footage)")
                    if !witness.notes.isEmpty { drawBody(witness.notes) }
                }
            }

            if !guidance.cards.filter({ $0.kind == .police || $0.kind == .emergency }).isEmpty {
                drawBody("Guidance flags at export", bold: true)
                for card in guidance.cards where card.kind == .police || card.kind == .emergency || card.kind == .eas {
                    drawBody(card.title, bold: true)
                    drawBody(card.body)
                }
            }

            if !input.photoImages.isEmpty {
                drawBody("Photographs", bold: true)
                for (kind, image) in input.photoImages {
                    let maxHeight: CGFloat = 220
                    let scale = min(contentWidth / max(image.size.width, 1), maxHeight / max(image.size.height, 1))
                    let drawSize = CGSize(width: image.size.width * scale, height: image.size.height * scale)
                    beginPageIfNeeded(requiredHeight: drawSize.height + 28)
                    drawBody(kind.displayName, bold: true)
                    image.draw(in: CGRect(x: margin, y: y, width: drawSize.width, height: drawSize.height))
                    y += drawSize.height + 12
                }
            }

            beginPageIfNeeded(requiredHeight: 80)
            drawBody("About this pack", bold: true)
            drawBody("This pack summarises what you recorded in Lyneqo. It is not an official European Accident Statement and is not a substitute for exchanging details, calling emergency services, or reporting to your insurer.")
        }
    }
}
