import Foundation
import UIKit

enum VehicleHistoryPDFBuilder {
    struct Input {
        let vehicleName: String
        let vehicleKind: VehicleKind
        let entries: [MaintenanceHistoryEntry]
    }

    static func buildPDF(input: Input) -> Data {
        let pageBounds = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: pageBounds)

        return renderer.pdfData { context in
            var y: CGFloat = 48
            let margin: CGFloat = 48
            let contentWidth = pageBounds.width - margin * 2

            func beginPageIfNeeded(requiredHeight: CGFloat) {
                if y + requiredHeight > pageBounds.height - margin {
                    context.beginPage()
                    y = margin
                }
            }

            func drawTitle(_ text: String) {
                beginPageIfNeeded(requiredHeight: 28)
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.boldSystemFont(ofSize: 20),
                    .foregroundColor: UIColor.label
                ]
                text.draw(at: CGPoint(x: margin, y: y), withAttributes: attrs)
                y += 28
            }

            func drawBody(_ text: String, bold: Bool = false) {
                let font = bold ? UIFont.boldSystemFont(ofSize: 12) : UIFont.systemFont(ofSize: 12)
                let paragraph = NSMutableParagraphStyle()
                paragraph.lineBreakMode = .byWordWrapping
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: UIColor.label,
                    .paragraphStyle: paragraph
                ]
                let measured = (text as NSString).boundingRect(
                    with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attrs,
                    context: nil
                )
                beginPageIfNeeded(requiredHeight: measured.height + 8)
                (text as NSString).draw(
                    in: CGRect(x: margin, y: y, width: contentWidth, height: measured.height),
                    withAttributes: attrs
                )
                y += measured.height + 8
            }

            context.beginPage()
            drawTitle("Vehicle History")
            drawBody("Generated by Lyneqo Caravan & Motorhome on \(Formatters.date(Date()))")
            drawBody("Vehicle", bold: true)
            drawBody(input.vehicleName.isEmpty ? input.vehicleKind.displayName : input.vehicleName)
            drawBody(input.vehicleKind.displayName)

            drawBody("Chronological timeline", bold: true)
            if input.entries.isEmpty {
                drawBody("No significant events recorded yet.")
            } else {
                for entry in input.entries {
                    drawBody("\(Formatters.date(entry.date)) · \(entry.title)", bold: true)
                    drawBody(entry.subtitle)
                }
            }

            beginPageIfNeeded(requiredHeight: 80)
            drawBody("About this report", bold: true)
            drawBody(
                "This timeline summarises maintenance, documents, faults and warranty events recorded in Lyneqo. Use it when selling your vehicle or supporting a warranty claim."
            )
        }
    }
}
