import Foundation
import SwiftData

enum WarrantyStore {
    @discardableResult
    static func createPlan(for vehicleID: UUID, in context: ModelContext) -> WarrantyPlan {
        let plan = WarrantyPlan(vehicleID: vehicleID)
        context.insert(plan)
        try? context.save()
        return plan
    }

    static func save(
        plan: WarrantyPlan,
        isUnderWarranty: Bool,
        warrantyExpiryDate: Date?,
        manufacturer: String,
        modelYear: Int?,
        purchaseDate: Date,
        purchaseCondition: WarrantyPurchaseCondition,
        ownershipType: WarrantyOwnershipType,
        warrantyType: String,
        durationYears: Int,
        handbookNotes: String,
        templateID: String?,
        motClass: UKMotorhomeMOTClass?,
        in context: ModelContext
    ) {
        plan.isUnderWarranty = isUnderWarranty
        plan.warrantyExpiryDate = warrantyExpiryDate
        plan.manufacturer = manufacturer.trimmingCharacters(in: .whitespacesAndNewlines)
        plan.modelYear = modelYear
        plan.purchaseDate = purchaseDate
        plan.purchaseCondition = purchaseCondition
        plan.ownershipType = ownershipType
        plan.warrantyType = warrantyType.trimmingCharacters(in: .whitespacesAndNewlines)
        plan.durationYears = max(1, durationYears)
        plan.handbookNotes = handbookNotes.trimmingCharacters(in: .whitespacesAndNewlines)
        plan.templateID = templateID
        plan.motClass = motClass
        plan.updatedAt = Date()
        try? context.save()
    }

    /// Drops manufacturer starter linkage so schedules fall back to custom windows.
    static func clearManufacturerTemplate(for vehicleID: UUID, in context: ModelContext) {
        let descriptor = FetchDescriptor<WarrantyPlan>(
            predicate: #Predicate { $0.vehicleID == vehicleID }
        )
        guard let plans = try? context.fetch(descriptor) else { return }
        for plan in plans where plan.templateID != nil {
            plan.templateID = nil
            plan.updatedAt = Date()
        }
        try? context.save()
    }

    @discardableResult
    static func createEvent(for plan: WarrantyPlan, in context: ModelContext) -> WarrantyEvent {
        let event = WarrantyEvent(vehicleID: plan.vehicleID)
        event.plan = plan
        let nextOrder = (plan.events ?? []).map(\.sortOrder).max().map { $0 + 1 } ?? 0
        event.sortOrder = nextOrder
        context.insert(event)
        try? context.save()
        return event
    }

    static func save(
        event: WarrantyEvent,
        yearNumber: Int,
        scheduledDate: Date,
        daysBefore: Int,
        daysAfter: Int,
        serviceType: WarrantyServiceType,
        requirementDescription: String,
        sortOrder: Int,
        isManual: Bool,
        completedDate: Date?,
        linkedDocumentIDs: [UUID],
        linkedMaintenanceID: UUID?,
        linkedFaultID: UUID?,
        in context: ModelContext
    ) {
        event.yearNumber = yearNumber
        event.scheduledDate = scheduledDate
        event.daysBefore = max(0, daysBefore)
        event.daysAfter = max(0, daysAfter)
        event.serviceType = serviceType
        event.requirementDescription = requirementDescription.trimmingCharacters(in: .whitespacesAndNewlines)
        event.sortOrder = sortOrder
        event.isManual = isManual
        event.completedDate = completedDate
        event.linkedDocumentIDs = linkedDocumentIDs
        event.linkedMaintenanceID = linkedMaintenanceID
        event.linkedFaultID = linkedFaultID
        event.updatedAt = Date()
        try? context.save()
    }

    static func delete(event: WarrantyEvent, in context: ModelContext) {
        for attachment in event.attachmentsList {
            MaintenanceAttachmentStore.delete(attachment, in: context)
        }
        context.delete(event)
        try? context.save()
    }

    static func delete(plan: WarrantyPlan, in context: ModelContext) {
        for event in plan.eventsList {
            delete(event: event, in: context)
        }
        context.delete(plan)
        try? context.save()
    }

    static func generateAnnualEvents(
        plan: WarrantyPlan,
        in context: ModelContext,
        kind: VehicleKind? = nil,
        ukMarket: Bool? = nil,
        replaceAutoGenerated: Bool = false
    ) {
        if replaceAutoGenerated {
            let toRemove = plan.eventsList.filter { !$0.isManual }
            for event in toRemove {
                delete(event: event, in: context)
            }
        }

        let existingAuto = plan.eventsList.filter { !$0.isManual }
        let existingHabitationYears = Set(
            existingAuto.filter { !$0.serviceType.isStatutoryInspection }.map(\.yearNumber)
        )
        let existingStatutoryYears = Set(
            existingAuto.filter { $0.serviceType.isStatutoryInspection }.map(\.yearNumber)
        )
        let calendar = Calendar.current
        let profile = vehicleProfile(for: plan.vehicleID, in: context)
        let resolvedKind = kind ?? profile?.kind ?? .caravan
        let resolvedUKMarket = ukMarket ?? profile?.warrantyUKMarket ?? true
        let template = WarrantySupport.patternOrCustom(id: plan.templateID, kind: resolvedKind)

        for year in 1...plan.durationYears {
            guard !existingHabitationYears.contains(year) else { continue }
            guard let scheduledDate = calendar.date(byAdding: .year, value: year, to: plan.purchaseDate) else {
                continue
            }

            let event = createEvent(for: plan, in: context)
            let window = template.window(forYear: year)
            let serviceType = template.serviceType(forYear: year)
            save(
                event: event,
                yearNumber: year,
                scheduledDate: scheduledDate,
                daysBefore: window.daysBefore,
                daysAfter: window.daysAfter,
                serviceType: serviceType,
                requirementDescription: template.requirement(forYear: year),
                sortOrder: year * 10,
                isManual: false,
                completedDate: nil,
                linkedDocumentIDs: [],
                linkedMaintenanceID: nil,
                linkedFaultID: nil,
                in: context
            )
        }

        guard resolvedKind == .motorhome else { return }

        if resolvedUKMarket {
            let motClass = plan.motClass
                ?? profile.map(WarrantySupport.suggestedMOTClass(for:))
                ?? .class4
            plan.motClass = motClass

            let firstYear = motClass.firstTestYear
            guard plan.durationYears >= firstYear else { return }

            for year in firstYear...plan.durationYears {
                guard !existingStatutoryYears.contains(year) else { continue }
                guard let scheduledDate = calendar.date(byAdding: .year, value: year, to: plan.purchaseDate) else {
                    continue
                }

                let event = createEvent(for: plan, in: context)
                save(
                    event: event,
                    yearNumber: year,
                    scheduledDate: scheduledDate,
                    daysBefore: motClass.daysBefore,
                    daysAfter: motClass.daysAfter,
                    serviceType: .mot,
                    requirementDescription: motClass.requirementDescription,
                    sortOrder: year * 10 + 1,
                    isManual: false,
                    completedDate: nil,
                    linkedDocumentIDs: [],
                    linkedMaintenanceID: nil,
                    linkedFaultID: nil,
                    in: context
                )
            }
            return
        }

        let firstYear = WarrantySupport.motorhomeVehicleInspectionFirstYear
        guard plan.durationYears >= firstYear else { return }

        for year in firstYear...plan.durationYears {
            guard !existingStatutoryYears.contains(year) else { continue }
            guard let scheduledDate = calendar.date(byAdding: .year, value: year, to: plan.purchaseDate) else {
                continue
            }

            let event = createEvent(for: plan, in: context)
            save(
                event: event,
                yearNumber: year,
                scheduledDate: scheduledDate,
                daysBefore: WarrantySupport.motorhomeVehicleInspectionDaysBefore,
                daysAfter: WarrantySupport.motorhomeVehicleInspectionDaysAfter,
                serviceType: .vehicleInspection,
                requirementDescription: WarrantyServiceType.vehicleInspection.defaultRequirementDescription,
                sortOrder: year * 10 + 1,
                isManual: false,
                completedDate: nil,
                linkedDocumentIDs: [],
                linkedMaintenanceID: nil,
                linkedFaultID: nil,
                in: context
            )
        }
    }

    private static func vehicleProfile(for vehicleID: UUID, in context: ModelContext) -> VehicleProfile? {
        let descriptor = FetchDescriptor<VehicleProfile>(
            predicate: #Predicate { $0.id == vehicleID }
        )
        return try? context.fetch(descriptor).first
    }
}
