import Foundation
import SwiftData

enum WarrantyStore {
    @discardableResult
    static func createPlan(for vehicleID: UUID, in context: ModelContext) -> WarrantyPlan {
        let plan = WarrantyPlan(vehicleID: vehicleID)
        context.insert(plan)
        try? context.save()
        return plan
    }

    static func save(
        plan: WarrantyPlan,
        isUnderWarranty: Bool,
        warrantyExpiryDate: Date?,
        manufacturer: String,
        modelYear: Int?,
        purchaseDate: Date,
        purchaseCondition: WarrantyPurchaseCondition,
        ownershipType: WarrantyOwnershipType,
        warrantyType: String,
        durationYears: Int,
        handbookNotes: String,
        templateID: String?,
        in context: ModelContext
    ) {
        plan.isUnderWarranty = isUnderWarranty
        plan.warrantyExpiryDate = warrantyExpiryDate
        plan.manufacturer = manufacturer.trimmingCharacters(in: .whitespacesAndNewlines)
        plan.modelYear = modelYear
        plan.purchaseDate = purchaseDate
        plan.purchaseCondition = purchaseCondition
        plan.ownershipType = ownershipType
        plan.warrantyType = warrantyType.trimmingCharacters(in: .whitespacesAndNewlines)
        plan.durationYears = max(1, durationYears)
        plan.handbookNotes = handbookNotes.trimmingCharacters(in: .whitespacesAndNewlines)
        plan.templateID = templateID
        plan.updatedAt = Date()
        try? context.save()
    }

    @discardableResult
    static func createEvent(for plan: WarrantyPlan, in context: ModelContext) -> WarrantyEvent {
        let event = WarrantyEvent(vehicleID: plan.vehicleID)
        event.plan = plan
        let nextOrder = (plan.events ?? []).map(\.sortOrder).max().map { $0 + 1 } ?? 0
        event.sortOrder = nextOrder
        context.insert(event)
        try? context.save()
        return event
    }

    static func save(
        event: WarrantyEvent,
        yearNumber: Int,
        scheduledDate: Date,
        daysBefore: Int,
        daysAfter: Int,
        serviceType: WarrantyServiceType,
        requirementDescription: String,
        sortOrder: Int,
        isManual: Bool,
        completedDate: Date?,
        linkedDocumentIDs: [UUID],
        linkedMaintenanceID: UUID?,
        linkedFaultID: UUID?,
        in context: ModelContext
    ) {
        event.yearNumber = yearNumber
        event.scheduledDate = scheduledDate
        event.daysBefore = max(0, daysBefore)
        event.daysAfter = max(0, daysAfter)
        event.serviceType = serviceType
        event.requirementDescription = requirementDescription.trimmingCharacters(in: .whitespacesAndNewlines)
        event.sortOrder = sortOrder
        event.isManual = isManual
        event.completedDate = completedDate
        event.linkedDocumentIDs = linkedDocumentIDs
        event.linkedMaintenanceID = linkedMaintenanceID
        event.linkedFaultID = linkedFaultID
        event.updatedAt = Date()
        try? context.save()
    }

    static func delete(event: WarrantyEvent, in context: ModelContext) {
        for attachment in event.attachmentsList {
            MaintenanceAttachmentStore.delete(attachment, in: context)
        }
        context.delete(event)
        try? context.save()
    }

    static func delete(plan: WarrantyPlan, in context: ModelContext) {
        for event in plan.eventsList {
            delete(event: event, in: context)
        }
        context.delete(plan)
        try? context.save()
    }

    static func generateAnnualEvents(
        plan: WarrantyPlan,
        in context: ModelContext,
        replaceAutoGenerated: Bool = false
    ) {
        if replaceAutoGenerated {
            let toRemove = plan.eventsList.filter { !$0.isManual }
            for event in toRemove {
                delete(event: event, in: context)
            }
        }

        let existingYears = Set(plan.eventsList.filter { !$0.isManual }.map(\.yearNumber))
        let calendar = Calendar.current

        for year in 1...plan.durationYears {
            guard !existingYears.contains(year) else { continue }
            guard let scheduledDate = calendar.date(byAdding: .year, value: year, to: plan.purchaseDate) else {
                continue
            }

            let event = createEvent(for: plan, in: context)
            let serviceType: WarrantyServiceType = year.isMultiple(of: 2) ? .serviceWithBodyCheck : .normalService
            save(
                event: event,
                yearNumber: year,
                scheduledDate: scheduledDate,
                daysBefore: 60,
                daysAfter: 30,
                serviceType: serviceType,
                requirementDescription: serviceType.defaultRequirementDescription,
                sortOrder: year,
                isManual: false,
                completedDate: nil,
                linkedDocumentIDs: [],
                linkedMaintenanceID: nil,
                linkedFaultID: nil,
                in: context
            )
        }
    }
}
