import SwiftData
import XCTest
@testable import loadMate3

@MainActor
final class WarrantySupportTests: XCTestCase {
    private var container: ModelContainer!
    private var context: ModelContext!

    override func setUpWithError() throws {
        container = try LoadMateModelContainer.makePreview()
        context = ModelContext(container)
    }

    override func tearDownWithError() throws {
        container = nil
        context = nil
    }

    func testGenerateAnnualEventsCreatesEightYearlyEvents() throws {
        let vehicleID = UUID()
        let purchaseDate = Calendar.current.date(from: DateComponents(year: 2020, month: 3, day: 12))!
        let plan = WarrantyPlan(vehicleID: vehicleID)
        plan.purchaseDate = purchaseDate
        plan.durationYears = 8
        context.insert(plan)

        WarrantyStore.generateAnnualEvents(plan: plan, in: context)

        XCTAssertEqual(plan.eventsList.count, 8)
        XCTAssertEqual(plan.eventsList.first?.yearNumber, 1)
        XCTAssertEqual(plan.eventsList.last?.yearNumber, 8)

        let yearOne = try XCTUnwrap(plan.eventsList.first)
        let expectedYearOne = Calendar.current.date(byAdding: .year, value: 1, to: purchaseDate)!
        XCTAssertEqual(
            Calendar.current.startOfDay(for: yearOne.scheduledDate),
            Calendar.current.startOfDay(for: expectedYearOne)
        )
    }

    func testManualEventsSurviveRegenerateWhenNotReplacing() throws {
        let vehicleID = UUID()
        let plan = WarrantyPlan(vehicleID: vehicleID)
        context.insert(plan)
        WarrantyStore.generateAnnualEvents(plan: plan, in: context)

        let manual = WarrantyStore.createEvent(for: plan, in: context)
        WarrantyStore.save(
            event: manual,
            yearNumber: 0,
            scheduledDate: Date(),
            daysBefore: 14,
            daysAfter: 7,
            serviceType: .custom,
            requirementDescription: "Special inspection",
            sortOrder: 99,
            isManual: true,
            completedDate: nil,
            linkedDocumentIDs: [],
            linkedMaintenanceID: nil,
            linkedFaultID: nil,
            in: context
        )

        WarrantyStore.generateAnnualEvents(plan: plan, in: context, replaceAutoGenerated: false)

        XCTAssertEqual(plan.eventsList.filter(\.isManual).count, 1)
        XCTAssertEqual(plan.eventsList.count, 9)
    }

    func testWindowStatusCalculation() throws {
        let event = WarrantyEvent(vehicleID: UUID())
        let scheduled = Calendar.current.date(from: DateComponents(year: 2026, month: 6, day: 15))!
        event.scheduledDate = scheduled
        event.daysBefore = 60
        event.daysAfter = 30

        let farBefore = Calendar.current.date(byAdding: .day, value: -61, to: scheduled)!
        XCTAssertEqual(WarrantySupport.status(for: event, now: farBefore), .upcoming)

        let inWindow = Calendar.current.date(byAdding: .day, value: -30, to: scheduled)!
        XCTAssertEqual(WarrantySupport.status(for: event, now: inWindow), .inWindow)

        let overdue = Calendar.current.date(byAdding: .day, value: 31, to: scheduled)!
        XCTAssertEqual(WarrantySupport.status(for: event, now: overdue), .overdue)

        event.completedDate = scheduled
        XCTAssertEqual(WarrantySupport.status(for: event, now: overdue), .completed)
    }

    func testCoverageStatusUsesDurationWhenNoExplicitExpiry() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.isUnderWarranty = true
        plan.purchaseDate = Calendar.current.date(byAdding: .year, value: -2, to: Date())!
        plan.durationYears = 8

        XCTAssertTrue(WarrantySupport.isCoverageActive(plan: plan))
        let expiry = try XCTUnwrap(WarrantySupport.expiresOn(plan: plan))
        XCTAssertEqual(
            Calendar.current.component(.year, from: expiry),
            Calendar.current.component(.year, from: plan.purchaseDate) + 8
        )
    }

    func testEventsSortBySortOrderThenDate() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        context.insert(plan)

        let later = WarrantyStore.createEvent(for: plan, in: context)
        WarrantyStore.save(
            event: later,
            yearNumber: 2,
            scheduledDate: Date(timeIntervalSince1970: 2_000),
            daysBefore: 60,
            daysAfter: 30,
            serviceType: .normalService,
            requirementDescription: "",
            sortOrder: 2,
            isManual: false,
            completedDate: nil,
            linkedDocumentIDs: [],
            linkedMaintenanceID: nil,
            linkedFaultID: nil,
            in: context
        )

        let earlier = WarrantyStore.createEvent(for: plan, in: context)
        WarrantyStore.save(
            event: earlier,
            yearNumber: 1,
            scheduledDate: Date(timeIntervalSince1970: 1_000),
            daysBefore: 60,
            daysAfter: 30,
            serviceType: .normalService,
            requirementDescription: "",
            sortOrder: 1,
            isManual: false,
            completedDate: nil,
            linkedDocumentIDs: [],
            linkedMaintenanceID: nil,
            linkedFaultID: nil,
            in: context
        )

        XCTAssertEqual(plan.eventsList.map(\.yearNumber), [1, 2])
    }
}
