import SwiftData
import XCTest
@testable import loadMate3

@MainActor
final class WarrantySupportTests: XCTestCase {
    private var container: ModelContainer!
    private var context: ModelContext!

    override func setUpWithError() throws {
        container = try LoadMateModelContainer.makePreview()
        context = ModelContext(container)
    }

    override func tearDownWithError() throws {
        container = nil
        context = nil
    }

    func testGenerateAnnualEventsCreatesEightYearlyEvents() throws {
        let vehicleID = UUID()
        let purchaseDate = Calendar.current.date(from: DateComponents(year: 2020, month: 3, day: 12))!
        let plan = WarrantyPlan(vehicleID: vehicleID)
        plan.purchaseDate = purchaseDate
        plan.durationYears = 8
        context.insert(plan)

        WarrantyStore.generateAnnualEvents(plan: plan, in: context)

        XCTAssertEqual(plan.eventsList.count, 8)
        XCTAssertEqual(plan.eventsList.first?.yearNumber, 1)
        XCTAssertEqual(plan.eventsList.last?.yearNumber, 8)

        let yearOne = try XCTUnwrap(plan.eventsList.first)
        let expectedYearOne = Calendar.current.date(byAdding: .year, value: 1, to: purchaseDate)!
        XCTAssertEqual(
            Calendar.current.startOfDay(for: yearOne.scheduledDate),
            Calendar.current.startOfDay(for: expectedYearOne)
        )
    }

    func testManualEventsSurviveRegenerateWhenNotReplacing() throws {
        let vehicleID = UUID()
        let plan = WarrantyPlan(vehicleID: vehicleID)
        context.insert(plan)
        WarrantyStore.generateAnnualEvents(plan: plan, in: context)

        let manual = WarrantyStore.createEvent(for: plan, in: context)
        WarrantyStore.save(
            event: manual,
            yearNumber: 0,
            scheduledDate: Date(),
            daysBefore: 14,
            daysAfter: 7,
            serviceType: .custom,
            requirementDescription: "Special inspection",
            sortOrder: 99,
            isManual: true,
            completedDate: nil,
            linkedDocumentIDs: [],
            linkedMaintenanceID: nil,
            linkedFaultID: nil,
            in: context
        )

        WarrantyStore.generateAnnualEvents(plan: plan, in: context, replaceAutoGenerated: false)

        XCTAssertEqual(plan.eventsList.filter(\.isManual).count, 1)
        XCTAssertEqual(plan.eventsList.count, 9)
    }

    func testWindowStatusCalculation() throws {
        let event = WarrantyEvent(vehicleID: UUID())
        let scheduled = Calendar.current.date(from: DateComponents(year: 2026, month: 6, day: 15))!
        event.scheduledDate = scheduled
        event.daysBefore = 60
        event.daysAfter = 30

        let farBefore = Calendar.current.date(byAdding: .day, value: -61, to: scheduled)!
        XCTAssertEqual(WarrantySupport.status(for: event, now: farBefore), .upcoming)

        let inWindow = Calendar.current.date(byAdding: .day, value: -30, to: scheduled)!
        XCTAssertEqual(WarrantySupport.status(for: event, now: inWindow), .inWindow)

        let overdue = Calendar.current.date(byAdding: .day, value: 31, to: scheduled)!
        XCTAssertEqual(WarrantySupport.status(for: event, now: overdue), .overdue)

        event.completedDate = scheduled
        XCTAssertEqual(WarrantySupport.status(for: event, now: overdue), .completed)
    }

    func testYearNumberDerivedFromDueDateVersusPurchase() {
        let purchase = Calendar.current.date(from: DateComponents(year: 2024, month: 2, day: 7))!

        let yearTwoExact = Calendar.current.date(from: DateComponents(year: 2026, month: 2, day: 7))!
        XCTAssertEqual(WarrantySupport.yearNumber(for: yearTwoExact, purchaseDate: purchase), 2)

        let twoYearsAndTwoMonths = Calendar.current.date(from: DateComponents(year: 2026, month: 4, day: 7))!
        XCTAssertEqual(WarrantySupport.yearNumber(for: twoYearsAndTwoMonths, purchaseDate: purchase), 2)

        let twoYearsAndSevenMonths = Calendar.current.date(from: DateComponents(year: 2026, month: 9, day: 7))!
        XCTAssertEqual(WarrantySupport.yearNumber(for: twoYearsAndSevenMonths, purchaseDate: purchase), 3)

        let beforePurchase = Calendar.current.date(from: DateComponents(year: 2023, month: 1, day: 1))!
        XCTAssertEqual(WarrantySupport.yearNumber(for: beforePurchase, purchaseDate: purchase), 0)

        XCTAssertEqual(WarrantySupport.yearNumber(for: purchase, purchaseDate: purchase), 0)
    }

    func testYearlyOccurrenceDatesIncludeStartAndAnnualSteps() {
        let start = Calendar.current.date(from: DateComponents(year: 2026, month: 9, day: 8))!
        let end = Calendar.current.date(from: DateComponents(year: 2029, month: 9, day: 8))!
        let dates = WarrantySupport.yearlyOccurrenceDates(from: start, through: end)
        XCTAssertEqual(dates.count, 4)
        XCTAssertEqual(
            dates.map { Calendar.current.component(.year, from: $0) },
            [2026, 2027, 2028, 2029]
        )
    }

    func testEnsureYearlyRepeatsCreatesFutureEventsWithoutDuplicates() throws {
        let vehicleID = UUID()
        let plan = WarrantyPlan(vehicleID: vehicleID)
        plan.purchaseDate = Calendar.current.date(from: DateComponents(year: 2024, month: 2, day: 7))!
        plan.durationYears = 5
        context.insert(plan)

        let start = Calendar.current.date(from: DateComponents(year: 2026, month: 9, day: 8))!
        let seed = WarrantyStore.createEvent(for: plan, in: context)
        WarrantyStore.save(
            event: seed,
            yearNumber: WarrantySupport.yearNumber(for: start, purchaseDate: plan.purchaseDate),
            scheduledDate: start,
            daysBefore: 60,
            daysAfter: 30,
            serviceType: .normalService,
            requirementDescription: "Fridge service",
            sortOrder: 10,
            isManual: true,
            completedDate: nil,
            linkedDocumentIDs: [],
            linkedMaintenanceID: nil,
            linkedFaultID: nil,
            in: context
        )

        let created = WarrantyStore.ensureYearlyRepeats(for: plan, matching: seed, in: context)
        XCTAssertFalse(created.isEmpty)
        XCTAssertTrue(plan.eventsList.contains(where: { Calendar.current.component(.year, from: $0.scheduledDate) == 2027 }))

        let again = WarrantyStore.ensureYearlyRepeats(for: plan, matching: seed, in: context)
        XCTAssertTrue(again.isEmpty)
    }

    func testOnlyNextFutureEventIsUpcomingOthersArePlanned() throws {
        let vehicleID = UUID()
        let year3 = WarrantyEvent(vehicleID: vehicleID)
        year3.scheduledDate = Calendar.current.date(from: DateComponents(year: 2027, month: 2, day: 7))!
        year3.daysBefore = 60
        year3.daysAfter = 30

        let year4 = WarrantyEvent(vehicleID: vehicleID)
        year4.scheduledDate = Calendar.current.date(from: DateComponents(year: 2028, month: 2, day: 7))!
        year4.daysBefore = 60
        year4.daysAfter = 30

        let year5 = WarrantyEvent(vehicleID: vehicleID)
        year5.scheduledDate = Calendar.current.date(from: DateComponents(year: 2029, month: 2, day: 7))!
        year5.daysBefore = 60
        year5.daysAfter = 30

        let events = [year3, year4, year5]
        let now = Calendar.current.date(from: DateComponents(year: 2026, month: 8, day: 7))!

        XCTAssertEqual(WarrantySupport.status(for: year3, among: events, now: now), .upcoming)
        XCTAssertEqual(WarrantySupport.status(for: year4, among: events, now: now), .planned)
        XCTAssertEqual(WarrantySupport.status(for: year5, among: events, now: now), .planned)
        XCTAssertEqual(WarrantySupport.statusDisplayName(for: .planned), "Planned")
    }

    func testPreparedEvidenceFiltersIncludeLinkedAndTypicalCategories() throws {
        let vehicleID = UUID()
        let event = WarrantyEvent(vehicleID: vehicleID)

        let warrantyDoc = DocumentRecord(vehicleID: vehicleID)
        warrantyDoc.category = .warranty
        let otherDoc = DocumentRecord(vehicleID: vehicleID)
        otherDoc.category = .insurance
        let linkedDoc = DocumentRecord(vehicleID: vehicleID)
        linkedDoc.category = .other
        event.linkedDocumentIDs = [linkedDoc.id]

        let docs = WarrantySupport.warrantyDocuments(
            from: [warrantyDoc, otherDoc, linkedDoc],
            events: [event]
        )
        XCTAssertEqual(Set(docs.map(\.id)), Set([warrantyDoc.id, linkedDoc.id]))

        let flagged = FaultRecord(vehicleID: vehicleID)
        flagged.isWarrantyRelated = true
        let unflagged = FaultRecord(vehicleID: vehicleID)
        let linkedFault = FaultRecord(vehicleID: vehicleID)
        event.linkedFaultID = linkedFault.id

        let faults = WarrantySupport.warrantyFaults(
            from: [flagged, unflagged, linkedFault],
            events: [event]
        )
        XCTAssertEqual(Set(faults.map(\.id)), Set([flagged.id, linkedFault.id]))
        XCTAssertEqual(
            WarrantySupport.unflaggedFaults(from: [flagged, unflagged, linkedFault], events: [event]).map(\.id),
            [unflagged.id]
        )

        let repair = MaintenanceRecord(vehicleID: vehicleID)
        repair.category = .warrantyRepair
        let damp = MaintenanceRecord(vehicleID: vehicleID)
        damp.category = .dampInspection
        let general = MaintenanceRecord(vehicleID: vehicleID)
        general.category = .generalMaintenance

        let repairs = WarrantySupport.warrantyRepairs(
            from: [repair, damp, general],
            events: [event]
        )
        XCTAssertEqual(Set(repairs.map(\.id)), Set([repair.id, damp.id]))
    }

    func testLinkableDocumentsExcludeCRiSAndOtherIdentityRecords() {
        let vehicleID = UUID()

        let warrantyDoc = DocumentRecord(vehicleID: vehicleID)
        warrantyDoc.category = .warranty
        warrantyDoc.title = "Manufacturer warranty"

        let flaggedOther = DocumentRecord(vehicleID: vehicleID)
        flaggedOther.category = .other
        flaggedOther.isWarrantyRelated = true

        let crisChip = DocumentRecord(vehicleID: vehicleID)
        crisChip.category = .vinChassisInformation
        crisChip.title = "CRiS VIN Chip"

        let crisRegistration = DocumentRecord(vehicleID: vehicleID)
        crisRegistration.category = .crisRegistration

        let insurance = DocumentRecord(vehicleID: vehicleID)
        insurance.category = .insurance

        let alreadyLinkedCRiS = DocumentRecord(vehicleID: vehicleID)
        alreadyLinkedCRiS.category = .vinChassisInformation
        alreadyLinkedCRiS.title = "CRiS VIN Chip (linked)"

        let docs = WarrantySupport.linkableDocuments(
            from: [warrantyDoc, flaggedOther, crisChip, crisRegistration, insurance, alreadyLinkedCRiS],
            alreadyLinkedIDs: [alreadyLinkedCRiS.id]
        )
        XCTAssertEqual(
            Set(docs.map(\.id)),
            Set([warrantyDoc.id, flaggedOther.id, alreadyLinkedCRiS.id])
        )
    }

    func testCoverageStatusUsesDurationWhenNoExplicitExpiry() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.isUnderWarranty = true
        plan.purchaseDate = Calendar.current.date(byAdding: .year, value: -2, to: Date())!
        plan.durationYears = 8

        XCTAssertTrue(WarrantySupport.isCoverageActive(plan: plan))
        let expiry = try XCTUnwrap(WarrantySupport.expiresOn(plan: plan))
        XCTAssertEqual(
            Calendar.current.component(.year, from: expiry),
            Calendar.current.component(.year, from: plan.purchaseDate) + 8
        )
    }

    func testEventsSortByScheduledDate() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        context.insert(plan)

        let laterDate = Calendar.current.date(from: DateComponents(year: 2028, month: 2, day: 7))!
        let earlierDate = Calendar.current.date(from: DateComponents(year: 2026, month: 10, day: 8))!

        let later = WarrantyStore.createEvent(for: plan, in: context)
        WarrantyStore.save(
            event: later,
            yearNumber: 2,
            scheduledDate: laterDate,
            daysBefore: 60,
            daysAfter: 30,
            serviceType: .normalService,
            requirementDescription: "",
            sortOrder: 1,
            isManual: false,
            completedDate: nil,
            linkedDocumentIDs: [],
            linkedMaintenanceID: nil,
            linkedFaultID: nil,
            in: context
        )

        let earlier = WarrantyStore.createEvent(for: plan, in: context)
        WarrantyStore.save(
            event: earlier,
            yearNumber: 1,
            scheduledDate: earlierDate,
            daysBefore: 60,
            daysAfter: 30,
            serviceType: .normalService,
            requirementDescription: "Manual service",
            sortOrder: 99,
            isManual: true,
            completedDate: nil,
            linkedDocumentIDs: [],
            linkedMaintenanceID: nil,
            linkedFaultID: nil,
            in: context
        )

        XCTAssertEqual(plan.eventsList.map(\.scheduledDate), [earlierDate, laterDate])
        XCTAssertEqual(plan.eventsList.map(\.id), [earlier.id, later.id])
    }

    func testSwiftCaravanPatternAppliesMilestoneWindows() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.durationYears = 10
        plan.templateID = "swift"
        context.insert(plan)

        WarrantyStore.generateAnnualEvents(plan: plan, in: context, kind: .caravan)

        XCTAssertEqual(plan.eventsList.count, 10)

        let yearOne = try XCTUnwrap(plan.eventsList.first { $0.yearNumber == 1 })
        XCTAssertEqual(yearOne.serviceType, .normalService)
        XCTAssertEqual(yearOne.daysBefore, 90)
        XCTAssertEqual(yearOne.daysAfter, 60)
        XCTAssertFalse(yearOne.isImportantMilestone)
        XCTAssertEqual(yearOne.displayTitle, "Year 1")
        XCTAssertEqual(
            WarrantySupport.windowSubtitle(for: yearOne),
            "Action window: 90 days before – 60 days after due date"
        )

        let yearThree = try XCTUnwrap(plan.eventsList.first { $0.yearNumber == 3 })
        XCTAssertEqual(yearThree.serviceType, .serviceWithBodyCheck)
        XCTAssertEqual(yearThree.daysBefore, 90)
        XCTAssertEqual(yearThree.daysAfter, 0)
        XCTAssertTrue(yearThree.isImportantMilestone)
        XCTAssertEqual(yearThree.displayTitle, "Year 3 · Milestone")
        XCTAssertEqual(
            WarrantySupport.windowSubtitle(for: yearThree),
            "Action window: 90 days before – must finish on or before the anniversary (no after-grace)"
        )
    }

    func testTenYearPatternGeneratesTenEvents() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.durationYears = 10
        plan.templateID = "adria"
        context.insert(plan)

        WarrantyStore.generateAnnualEvents(plan: plan, in: context, kind: .caravan)

        XCTAssertEqual(plan.eventsList.count, 10)
    }

    func testPickerOptionsUseMotorhomeCatalogForMotorhomeProfiles() throws {
        let caravan = TestFixtures.caravanProfile()
        caravan.warrantyUKMarket = true
        let motorhome = TestFixtures.motorhomeProfile()
        motorhome.warrantyUKMarket = true

        let caravanIDs = Set(WarrantySupport.pickerOptions(for: caravan).map(\.id))
        let motorhomeIDs = Set(WarrantySupport.pickerOptions(for: motorhome).map(\.id))

        XCTAssertFalse(caravanIDs.contains("auto-trail"))
        XCTAssertFalse(caravanIDs.contains("hobby"))
        XCTAssertFalse(caravanIDs.contains("bailey-campervan"))

        XCTAssertTrue(motorhomeIDs.isSuperset(of: [
            "swift", "bailey", "bailey-campervan", "coachman", "elddis",
            "adria", "auto-trail", "chausson", "burstner", "hobby",
        ]))
    }

    func testMotorhomeCatalogIncludesDistinctBrandsAndWindows() throws {
        let ids = Set(MotorhomeWarrantyPatternCatalog.manufacturerGuides.map(\.id))
        XCTAssertTrue(ids.isSuperset(of: [
            "swift", "bailey", "bailey-campervan", "coachman", "elddis",
            "adria", "auto-trail", "chausson", "burstner", "hobby",
        ]))

        let autoTrail = try XCTUnwrap(MotorhomeWarrantyPatternCatalog.pattern(id: "auto-trail"))
        XCTAssertEqual(autoTrail.durationYears, 5)
        XCTAssertEqual(autoTrail.window(forYear: 1), WarrantyServiceWindow(daysBefore: 30, daysAfter: 30))
        XCTAssertEqual(autoTrail.window(forYear: 5), WarrantyServiceWindow(daysBefore: 30, daysAfter: 0))
        XCTAssertEqual(autoTrail.serviceType(forYear: 5), .serviceWithBodyCheck)

        let baileyCamper = try XCTUnwrap(MotorhomeWarrantyPatternCatalog.pattern(id: "bailey-campervan"))
        XCTAssertEqual(baileyCamper.durationYears, 3)
        XCTAssertEqual(baileyCamper.window(forYear: 3).daysAfter, 0)

        let hobby = try XCTUnwrap(MotorhomeWarrantyPatternCatalog.pattern(id: "hobby"))
        XCTAssertEqual(hobby.durationYears, 12)
    }

    func testMotorhomeAutoTrailPatternGeneratesMilestoneEvents() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.durationYears = 5
        plan.templateID = "auto-trail"
        plan.motClass = .class4
        context.insert(plan)

        WarrantyStore.generateAnnualEvents(plan: plan, in: context, kind: .motorhome, ukMarket: true)

        let habitation = plan.eventsList.filter { !$0.serviceType.isStatutoryInspection }
        let mots = plan.eventsList.filter { $0.serviceType == .mot }

        XCTAssertEqual(habitation.count, 5)
        XCTAssertEqual(mots.count, 3)
        XCTAssertEqual(mots.map(\.yearNumber), [3, 4, 5])

        let yearOne = try XCTUnwrap(habitation.first { $0.yearNumber == 1 })
        XCTAssertEqual(yearOne.serviceType, .normalService)
        XCTAssertEqual(yearOne.daysBefore, 30)
        XCTAssertEqual(yearOne.daysAfter, 30)

        let yearFive = try XCTUnwrap(habitation.first { $0.yearNumber == 5 })
        XCTAssertEqual(yearFive.serviceType, .serviceWithBodyCheck)
        XCTAssertEqual(yearFive.daysBefore, 30)
        XCTAssertEqual(yearFive.daysAfter, 0)

        let firstMOT = try XCTUnwrap(mots.first { $0.yearNumber == 3 })
        XCTAssertEqual(firstMOT.displayTitle, "Year 3 Class 4 MOT")
        XCTAssertEqual(firstMOT.daysBefore, UKMotorhomeMOTClass.class4.daysBefore)
        XCTAssertEqual(firstMOT.daysAfter, UKMotorhomeMOTClass.class4.daysAfter)
        XCTAssertEqual(firstMOT.sortOrder, 31)
    }

    func testMotorhomeScheduleAddsMOTFromYearThree() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.durationYears = 6
        plan.templateID = "bailey"
        plan.motClass = .class7
        context.insert(plan)

        WarrantyStore.generateAnnualEvents(plan: plan, in: context, kind: .motorhome, ukMarket: true)

        let mots = plan.eventsList.filter { $0.serviceType == .mot }
        XCTAssertEqual(mots.map(\.yearNumber), [3, 4, 5, 6])
        XCTAssertEqual(try XCTUnwrap(mots.first).displayTitle, "Year 3 Class 7 MOT")
        XCTAssertTrue(mots.allSatisfy { !$0.isManual })
        XCTAssertEqual(plan.eventsList.count, 10) // 6 habitation + 4 MOT
    }

    func testUKMotorhomeHGVClassAddsAnnualTestFromYearOne() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.durationYears = 4
        plan.templateID = "swift"
        plan.motClass = .hgvAnnual
        context.insert(plan)

        WarrantyStore.generateAnnualEvents(plan: plan, in: context, kind: .motorhome, ukMarket: true)

        let tests = plan.eventsList.filter { $0.serviceType == .mot }
        XCTAssertEqual(tests.map(\.yearNumber), [1, 2, 3, 4])
        XCTAssertEqual(try XCTUnwrap(tests.first).displayTitle, "Year 1 HGV annual test")
        XCTAssertEqual(plan.motClass, .hgvAnnual)
    }

    func testSuggestedMOTClassUsesPlatedMass() {
        XCTAssertEqual(UKMotorhomeMOTClass.suggested(forPlatedMassKg: 2_800), .class4)
        XCTAssertEqual(UKMotorhomeMOTClass.suggested(forPlatedMassKg: 3_200), .class7)
        XCTAssertEqual(UKMotorhomeMOTClass.suggested(forPlatedMassKg: 3_500), .class7)
        XCTAssertEqual(UKMotorhomeMOTClass.suggested(forPlatedMassKg: 3_501), .hgvAnnual)
        XCTAssertEqual(UKMotorhomeMOTClass.suggested(forPlatedMassKg: 0), .class4)
    }

    func testNonUKMotorhomeScheduleAddsVehicleInspectionFromYearThree() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.durationYears = 6
        plan.templateID = "bailey"
        context.insert(plan)

        WarrantyStore.generateAnnualEvents(plan: plan, in: context, kind: .motorhome, ukMarket: false)

        let inspections = plan.eventsList.filter { $0.serviceType == .vehicleInspection }
        XCTAssertEqual(inspections.map(\.yearNumber), [3, 4, 5, 6])
        XCTAssertTrue(plan.eventsList.allSatisfy { $0.serviceType != .mot })
        XCTAssertEqual(plan.eventsList.count, 10) // 6 habitation + 4 inspections

        let first = try XCTUnwrap(inspections.first { $0.yearNumber == 3 })
        XCTAssertEqual(first.displayTitle, "Year 3 vehicle inspection")
        XCTAssertEqual(first.daysBefore, WarrantySupport.motorhomeVehicleInspectionDaysBefore)
        XCTAssertEqual(first.daysAfter, WarrantySupport.motorhomeVehicleInspectionDaysAfter)
    }

    func testCaravanScheduleDoesNotAddStatutoryInspectionEvents() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.durationYears = 6
        plan.templateID = "bailey"
        context.insert(plan)

        WarrantyStore.generateAnnualEvents(plan: plan, in: context, kind: .caravan, ukMarket: true)

        XCTAssertEqual(plan.eventsList.count, 6)
        XCTAssertTrue(plan.eventsList.allSatisfy { !$0.serviceType.isStatutoryInspection })
    }

    func testInsuranceStartDateCreatesYearlyActions() throws {
        let profile = VehicleProfile(name: "Test van", kind: .caravan)
        let start = Calendar.current.date(from: DateComponents(year: 2024, month: 3, day: 15))!
        profile.insuranceStartDate = start
        context.insert(profile)

        let now = Calendar.current.date(from: DateComponents(year: 2026, month: 8, day: 8))!
        WarrantyStore.syncInsuranceRenewalEvents(for: profile, in: context, now: now)

        let plans = try context.fetch(FetchDescriptor<WarrantyPlan>())
        let storedPlan = try XCTUnwrap(plans.first { $0.vehicleID == profile.id })

        let insuranceEvents = storedPlan.eventsList.filter { $0.serviceType == .insuranceRenewal }
        XCTAssertEqual(
            Set(insuranceEvents.map { Calendar.current.startOfDay(for: $0.scheduledDate) }),
            Set(WarrantySupport.insuranceRenewalDates(from: start, now: now).map { Calendar.current.startOfDay(for: $0) })
        )
        XCTAssertEqual(
            insuranceEvents.first?.requirementDescription,
            "Ensure your vehicle, ensure your reg, ensure your caravan."
        )
        XCTAssertEqual(insuranceEvents.first?.daysBefore, WarrantySupport.insuranceRenewalDaysBefore)
        XCTAssertEqual(insuranceEvents.first?.displayTitle, "Insurance")
    }

    func testInsuranceStartDateUsesMotorhomeWording() throws {
        let profile = VehicleProfile(name: "Test MH", kind: .motorhome)
        profile.insuranceStartDate = Calendar.current.date(from: DateComponents(year: 2025, month: 1, day: 10))
        context.insert(profile)

        WarrantyStore.syncInsuranceRenewalEvents(for: profile, in: context)

        let plans = try context.fetch(FetchDescriptor<WarrantyPlan>())
        let plan = try XCTUnwrap(plans.first { $0.vehicleID == profile.id })
        let event = try XCTUnwrap(plan.eventsList.first { $0.serviceType == .insuranceRenewal })
        XCTAssertEqual(event.requirementDescription, "Ensure your vehicle, ensure your reg, ensure your motorhome.")
    }

    func testClearingInsuranceStartRemovesOpenInsuranceEvents() throws {
        let profile = VehicleProfile(name: "Test van", kind: .caravan)
        profile.insuranceStartDate = Calendar.current.date(from: DateComponents(year: 2024, month: 6, day: 1))
        context.insert(profile)

        WarrantyStore.syncInsuranceRenewalEvents(for: profile, in: context)
        let plans = try context.fetch(FetchDescriptor<WarrantyPlan>())
        let plan = try XCTUnwrap(plans.first { $0.vehicleID == profile.id })
        XCTAssertFalse(plan.eventsList.filter { $0.serviceType == .insuranceRenewal }.isEmpty)

        profile.insuranceStartDate = nil
        WarrantyStore.syncInsuranceRenewalEvents(for: profile, in: context)

        XCTAssertTrue(plan.eventsList.filter { $0.serviceType == .insuranceRenewal }.isEmpty)
    }

    func testAnnualCostsUseSingleRecordedCost() {
        let event = WarrantyEvent(vehicleID: UUID())
        event.scheduledDate = Calendar.current.date(from: DateComponents(year: 2028, month: 8, day: 14))!
        event.actualCost = 325

        let years = WarrantySupport.annualCosts(events: [event], maintenanceRecords: [], faults: [])
        XCTAssertEqual(years.count, 1)
        XCTAssertEqual(years[0].year, 2028)
        XCTAssertEqual(years[0].total, 325)
        XCTAssertEqual(years[0].itemCount, 1)
        XCTAssertEqual(event.cost, 325)
    }

    func testCustomCostItemUsesItsNameInWarrantyYearTitle() {
        let event = WarrantyEvent(vehicleID: UUID())
        event.yearNumber = 2
        event.serviceType = .custom
        event.requirementDescription = "Storage"
        event.actualCost = 100

        XCTAssertEqual(event.displayTitle, "Year 2 · Storage")
        XCTAssertEqual(event.costItemName, "Storage")
        XCTAssertEqual(event.cost, 100)
    }

    func testCostItemNestsUnderItsServiceAndCountsTowardsYearlyCosts() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.purchaseDate = Calendar.current.date(from: DateComponents(year: 2024, month: 2, day: 7))!
        plan.durationYears = 3
        context.insert(plan)
        WarrantyStore.generateAnnualEvents(plan: plan, in: context)

        let yearTwo = try XCTUnwrap(plan.eventsList.first { $0.yearNumber == 2 })
        yearTwo.actualCost = 350
        let item = addStorageItem(to: yearTwo, in: plan, amount: 100)

        XCTAssertFalse(plan.timelineEvents.contains { $0.id == item.id })
        XCTAssertEqual(plan.costItems(for: yearTwo).map(\.id), [item.id])
        XCTAssertEqual(WarrantySupport.combinedCost(for: yearTwo, items: [item]), 450)

        let itemYear = Calendar.current.component(.year, from: item.scheduledDate)
        let years = WarrantySupport.annualCosts(
            events: plan.eventsList,
            maintenanceRecords: [],
            faults: []
        )
        let costsForItemYear = try XCTUnwrap(years.first { $0.year == itemYear })
        XCTAssertEqual(costsForItemYear.total, 450)
    }

    func testDeletingServiceAlsoDeletesItsCostItems() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.purchaseDate = Calendar.current.date(from: DateComponents(year: 2024, month: 2, day: 7))!
        plan.durationYears = 3
        context.insert(plan)
        WarrantyStore.generateAnnualEvents(plan: plan, in: context)

        let yearTwo = try XCTUnwrap(plan.eventsList.first { $0.yearNumber == 2 })
        let item = addStorageItem(to: yearTwo, in: plan, amount: 100)
        let itemID = item.id

        WarrantyStore.delete(event: yearTwo, in: context)

        XCTAssertFalse(plan.eventsList.contains { $0.id == itemID })
        XCTAssertTrue(plan.eventsList.allSatisfy { $0.yearNumber != 2 })
    }

    func testCostItemsAreNotOfferedAsReminders() throws {
        let plan = WarrantyPlan(vehicleID: UUID())
        plan.purchaseDate = Calendar.current.date(from: DateComponents(year: 2024, month: 2, day: 7))!
        plan.durationYears = 3
        context.insert(plan)
        WarrantyStore.generateAnnualEvents(plan: plan, in: context)

        let yearTwo = try XCTUnwrap(plan.eventsList.first { $0.yearNumber == 2 })
        let item = addStorageItem(to: yearTwo, in: plan, amount: 100)

        let reminders = WarrantySupport.reminderItems(plans: [plan], vehicleID: plan.vehicleID)
        XCTAssertFalse(reminders.contains { $0.eventID == item.id })
        XCTAssertTrue(reminders.contains { $0.eventID == yearTwo.id })
    }

    @discardableResult
    private func addStorageItem(
        to parent: WarrantyEvent,
        in plan: WarrantyPlan,
        amount: Double
    ) -> WarrantyEvent {
        let item = WarrantyStore.createEvent(for: plan, in: context)
        WarrantyStore.save(
            event: item,
            yearNumber: parent.yearNumber,
            scheduledDate: parent.scheduledDate,
            daysBefore: 0,
            daysAfter: 0,
            serviceType: .custom,
            requirementDescription: "Storage",
            sortOrder: item.sortOrder,
            isManual: true,
            completedDate: nil,
            linkedDocumentIDs: [],
            linkedMaintenanceID: nil,
            linkedFaultID: nil,
            parentEventID: parent.id,
            cost: amount,
            in: context
        )
        return item
    }

    func testAnnualCostsGroupByCalendarYearUsingCompletionWhenPresent() {
        let vehicleID = UUID()
        let scheduled2028 = WarrantyEvent(vehicleID: vehicleID)
        scheduled2028.scheduledDate = Calendar.current.date(from: DateComponents(year: 2028, month: 8, day: 14))!
        scheduled2028.actualCost = 200

        let completedIn2029 = WarrantyEvent(vehicleID: vehicleID)
        completedIn2029.scheduledDate = Calendar.current.date(from: DateComponents(year: 2028, month: 8, day: 14))!
        completedIn2029.completedDate = Calendar.current.date(from: DateComponents(year: 2029, month: 1, day: 5))!
        completedIn2029.actualCost = 250

        let years = WarrantySupport.annualCosts(
            events: [scheduled2028, completedIn2029],
            maintenanceRecords: [],
            faults: []
        )
        XCTAssertEqual(years.map(\.year), [2028, 2029])
        XCTAssertEqual(years[0].total, 200)
        XCTAssertEqual(years[0].itemCount, 1)
        XCTAssertEqual(years[1].total, 250)
        XCTAssertEqual(years[1].itemCount, 1)
    }

    func testEnsureYearlyRepeatsDoNotCopyCost() throws {
        let vehicleID = UUID()
        let plan = WarrantyPlan(vehicleID: vehicleID)
        plan.purchaseDate = Calendar.current.date(from: DateComponents(year: 2024, month: 2, day: 7))!
        plan.durationYears = 5
        context.insert(plan)

        let start = Calendar.current.date(from: DateComponents(year: 2026, month: 9, day: 8))!
        let seed = WarrantyStore.createEvent(for: plan, in: context)
        WarrantyStore.save(
            event: seed,
            yearNumber: WarrantySupport.yearNumber(for: start, purchaseDate: plan.purchaseDate),
            scheduledDate: start,
            daysBefore: 60,
            daysAfter: 30,
            serviceType: .custom,
            requirementDescription: "Storage",
            sortOrder: 10,
            isManual: true,
            completedDate: nil,
            linkedDocumentIDs: [],
            linkedMaintenanceID: nil,
            linkedFaultID: nil,
            cost: 165,
            in: context
        )

        let created = WarrantyStore.ensureYearlyRepeats(for: plan, matching: seed, in: context)
        XCTAssertFalse(created.isEmpty)
        XCTAssertEqual(seed.actualCost, 165)
        for copy in created {
            XCTAssertNil(copy.actualCost)
        }
    }

    func testAnnualCostsIncludeMaintenanceAndFaults() {
        let vehicleID = UUID()
        let maintenance = MaintenanceRecord(vehicleID: vehicleID)
        maintenance.serviceDate = Calendar.current.date(from: DateComponents(year: 2027, month: 3, day: 1))!
        maintenance.cost = 90

        let fault = FaultRecord(vehicleID: vehicleID)
        fault.discoveredDate = Calendar.current.date(from: DateComponents(year: 2027, month: 6, day: 10))!
        fault.actualRepairCost = 40

        let years = WarrantySupport.annualCosts(
            events: [],
            maintenanceRecords: [maintenance],
            faults: [fault]
        )
        XCTAssertEqual(years.count, 1)
        XCTAssertEqual(years[0].year, 2027)
        XCTAssertEqual(years[0].total, 130)
        XCTAssertEqual(years[0].itemCount, 2)
        XCTAssertEqual(years[0].detail, "2 costs")
    }

    func testAnnualCostsDeduplicateLinkedRecordsPreferringActual() {
        let vehicleID = UUID()
        let maintenance = MaintenanceRecord(vehicleID: vehicleID)
        maintenance.serviceDate = Calendar.current.date(from: DateComponents(year: 2026, month: 4, day: 1))!
        maintenance.cost = 150

        let event = WarrantyEvent(vehicleID: vehicleID)
        event.scheduledDate = Calendar.current.date(from: DateComponents(year: 2026, month: 4, day: 2))!
        event.estimatedCost = 100
        event.linkedMaintenanceID = maintenance.id

        let years = WarrantySupport.annualCosts(
            events: [event],
            maintenanceRecords: [maintenance],
            faults: []
        )
        XCTAssertEqual(years.count, 1)
        XCTAssertEqual(years[0].total, 150)
        XCTAssertEqual(years[0].itemCount, 1)
    }

    func testAnnualCostsDeduplicateFaultLinkedToMaintenance() {
        let vehicleID = UUID()
        let maintenance = MaintenanceRecord(vehicleID: vehicleID)
        maintenance.serviceDate = Calendar.current.date(from: DateComponents(year: 2026, month: 5, day: 1))!
        maintenance.cost = 200

        let fault = FaultRecord(vehicleID: vehicleID)
        fault.discoveredDate = Calendar.current.date(from: DateComponents(year: 2026, month: 5, day: 2))!
        fault.actualRepairCost = 220
        fault.linkedMaintenanceRecord = maintenance

        let years = WarrantySupport.annualCosts(
            events: [],
            maintenanceRecords: [maintenance],
            faults: [fault]
        )
        XCTAssertEqual(years.count, 1)
        XCTAssertEqual(years[0].total, 220)
        XCTAssertEqual(years[0].itemCount, 1)
    }

    func testAnnualCostsOmitYearsWithNoAmounts() {
        let event = WarrantyEvent(vehicleID: UUID())
        event.scheduledDate = Calendar.current.date(from: DateComponents(year: 2030, month: 1, day: 1))!

        let years = WarrantySupport.annualCosts(events: [event], maintenanceRecords: [], faults: [])
        XCTAssertTrue(years.isEmpty)
    }

    func testCostCaptionPromptsWhenMissingAndShowsAmountWhenPresent() {
        let event = WarrantyEvent(vehicleID: UUID())
        XCTAssertEqual(WarrantySupport.costCaption(for: event), "Add cost")
        XCTAssertFalse(WarrantySupport.hasRecordedCost(for: event))

        event.actualCost = 250
        XCTAssertEqual(WarrantySupport.costCaption(for: event), Formatters.currency(250))
        XCTAssertTrue(WarrantySupport.hasRecordedCost(for: event))
    }
}
